services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:80"
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "4000:8080"