services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      BASE_BACKEND_URL: http://100.103.10.60:8080
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "4000:8080"